# Generated by Django 5.0 on 2023-12-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctors',
            new_name='doctorsData',
        ),
    ]
