# Generated by Django 5.0 on 2023-12-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_data',
            field=models.DateField(),
        ),
    ]
