# Generated by Django 5.0 on 2023-12-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_bookingmodel_booked_on_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingModel',
            new_name='Booking',
        ),
    ]
