# Generated by Django 5.0 on 2023-12-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_rename_bookingmodel_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='booking_date',
        ),
    ]
